# Generated by Django 4.0.6 on 2022-07-18 06:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('address', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.TextField()),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depAndemp.department')),
            ],
        ),
    ]
