# Generated by Django 4.0.6 on 2022-07-19 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_options'),
        ('hireAndOrder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.AddField(
            model_name='orders',
            name='cartitems',
            field=models.ManyToManyField(to='hireAndOrder.cartitem'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 23, 35, 36, 224457), editable=False, null=True),
        ),
    ]
