# Generated by Django 4.0.6 on 2022-07-19 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hireAndOrder', '0002_rename_cart_cartitem_remove_orders_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 23, 48, 2, 489381), editable=False, null=True),
        ),
        migrations.CreateModel(
            name='OrderTransection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_code', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hireAndOrder.orders')),
            ],
        ),
        migrations.CreateModel(
            name='HireTransection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_code', models.CharField(max_length=400)),
                ('status', models.BooleanField(default=False)),
                ('hire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hireAndOrder.hire')),
            ],
        ),
    ]
