# Generated by Django 4.0.6 on 2022-08-04 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireAndOrder', '0006_orders_prod_quantity_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 4, 21, 58, 26, 165857)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 23, 58, 26, 165857), editable=False, null=True),
        ),
    ]
