# Generated by Django 4.0.6 on 2022-08-06 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireAndOrder', '0009_alter_orders_date_alter_orders_prod_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 15, 50, 8, 923017)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 17, 50, 8, 923017), editable=False, null=True),
        ),
    ]
