# Generated by Django 4.0.6 on 2022-08-09 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireAndOrder', '0011_alter_hire_user_id_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 15, 17, 55, 751001)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 17, 17, 55, 751001), editable=False, null=True),
        ),
    ]
