# Generated by Django 4.0.6 on 2022-07-13 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter the number that starts with 9 and has 10 digits.', regex='^\\??\\d{9,11}$')])),
                ('store_description', models.TextField()),
            ],
        ),
    ]
