# Generated by Django 4.0.6 on 2022-07-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_recent',
            field=models.BooleanField(default=False),
        ),
    ]
